Repository CinEffi/backend, pull requests merged in 2024-04, with the labels that each got.

#9 Refactor/set column order
  .gitignore
  cineffi/src/main/java/shinzo/cineffi/CineffiApplication.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/BaseEntity.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/movie/Actor.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/movie/ActorMovie.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/movie/AvgScore.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/movie/Movie.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/review/Review.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/user/Follow.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/user/Report.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/user/UserAccount.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/user/UserActivityNum.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/user/UserCore.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/user/UserProfile.java
  cineffi/src/main/resources/application.yml
Labels: refactor

#14 feat : responseDTO & exception, messages #13
  cineffi/src/main/java/shinzo/cineffi/domain/dto/ResponseDTO.java
  cineffi/src/main/java/shinzo/cineffi/exception/CustomException.java
  cineffi/src/main/java/shinzo/cineffi/exception/GlobalExceptionHandler.java
  cineffi/src/main/java/shinzo/cineffi/exception/message/ErrorMsg.java
  cineffi/src/main/java/shinzo/cineffi/exception/message/SuccessMsg.java
Labels: feat

#23 chore : .gitignore all the files in ./idea
  .gitignore
Labels: chore

#33 Feat/mail login#21
  .gitignore
  cineffi/build.gradle
  cineffi/src/main/java/shinzo/cineffi/auth/AuthController.java
  cineffi/src/main/java/shinzo/cineffi/auth/AuthRepository.java
  cineffi/src/main/java/shinzo/cineffi/auth/AuthService.java
  cineffi/src/main/java/shinzo/cineffi/auth/MailController.java
  cineffi/src/main/java/shinzo/cineffi/auth/MailService.java
  cineffi/src/main/java/shinzo/cineffi/auth/repository/AuthCodeRepository.java
  cineffi/src/main/java/shinzo/cineffi/config/CorsMvcConfig.java
  cineffi/src/main/java/shinzo/cineffi/config/SecurityConfig.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/AuthCodeDTO.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/AuthRequestDTO.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/EmailRequestDTO.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/KakaoProfile.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/KakaoToken.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/LoginRequestDTO.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/NickNameDTO.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/review/Review.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/user/AuthCode.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/user/UserAccount.java
  cineffi/src/main/java/shinzo/cineffi/exception/message/ErrorMsg.java
  cineffi/src/main/java/shinzo/cineffi/jwt/CustomAuthenticatedUser.java
  cineffi/src/main/java/shinzo/cineffi/jwt/JWTFilter.java
  cineffi/src/main/java/shinzo/cineffi/jwt/JWTProvider.java
  cineffi/src/main/java/shinzo/cineffi/jwt/JWTUtil.java
  cineffi/src/main/java/shinzo/cineffi/jwt/JWToken.java
  cineffi/src/main/java/shinzo/cineffi/user/UserController.java
  cineffi/src/main/java/shinzo/cineffi/user/UserService.java
  cineffi/src/main/java/shinzo/cineffi/user/repository/UserAccountRepository.java
  cineffi/src/main/java/shinzo/cineffi/user/repository/UserAccountRepositoryCustom.java
  cineffi/src/main/java/shinzo/cineffi/user/repository/UserAccountRepositoryImpl.java
  cineffi/src/main/java/shinzo/cineffi/user/repository/UserRepository.java
  cineffi/src/main/resources/application.yml
Labels: feat
