Repository CinEffi/backend, pull requests merged in 2024-05, with the labels that each got.

#39 Feat: user API 개발 #34
  cineffi/src/main/java/shinzo/cineffi/domain/dto/GetMyPageRes.java
  cineffi/src/main/java/shinzo/cineffi/exception/message/ErrorMsg.java
  cineffi/src/main/java/shinzo/cineffi/movie/ScrapService.java
  cineffi/src/main/java/shinzo/cineffi/movie/repository/ScrapRepository.java
  cineffi/src/main/java/shinzo/cineffi/review/ReviewService.java
  cineffi/src/main/java/shinzo/cineffi/review/repository/ReviewRepository.java
  cineffi/src/main/java/shinzo/cineffi/user/EditProfileReq.java
  cineffi/src/main/java/shinzo/cineffi/user/FollowController.java
  cineffi/src/main/java/shinzo/cineffi/user/FollowReq.java
  cineffi/src/main/java/shinzo/cineffi/user/FollowService.java
  cineffi/src/main/java/shinzo/cineffi/user/GetFollowRes.java
  cineffi/src/main/java/shinzo/cineffi/user/GetProfileRes.java
  cineffi/src/main/java/shinzo/cineffi/user/GetReviewRes.java
  cineffi/src/main/java/shinzo/cineffi/user/GetScrapRes.java
  cineffi/src/main/java/shinzo/cineffi/user/ImageConverter.java
  cineffi/src/main/java/shinzo/cineffi/user/UserController.java
  cineffi/src/main/java/shinzo/cineffi/user/UserService.java
  cineffi/src/main/java/shinzo/cineffi/user/repository/FollowRepository.java
  cineffi/src/main/resources/application.yml
  cineffi/src/test/java/shinzo/cineffi/movieTest.java
Labels: feat

#48 Fix/fix user review#47
  cineffi/.gitignore
  cineffi/src/main/java/shinzo/cineffi/config/InitService.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/movie/AvgScore.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/review/Review.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/review/ReviewLike.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/score/Score.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/user/UserActivityNum.java
  cineffi/src/main/java/shinzo/cineffi/review/ReviewService.java
  cineffi/src/main/java/shinzo/cineffi/score/ScoreService.java
  cineffi/src/test/java/shinzo/cineffi/movieTest.java
Labels: fix

#54 refactor: DailyMovie -> BoxOfficeMovie로 이름변경#12
  cineffi/.idea/compiler.xml
  cineffi/.idea/dataSources.xml
  cineffi/src/main/java/shinzo/cineffi/domain/entity/movie/BoxOfficeMovie.java
  cineffi/src/main/java/shinzo/cineffi/movie/BoxOfficeDataHandler.java
  cineffi/src/main/java/shinzo/cineffi/movie/MovieController.java
  cineffi/src/main/java/shinzo/cineffi/movie/MovieService.java
  cineffi/src/main/java/shinzo/cineffi/movie/repository/BoxOfficeMovieRepository.java
Labels: refactor

#56 Fix/user collection scrap list api#55
  cineffi/src/main/java/shinzo/cineffi/config/InitService.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/ScrapDto.java
  cineffi/src/main/java/shinzo/cineffi/movie/ScrapService.java
  cineffi/src/main/java/shinzo/cineffi/review/ReviewService.java
  cineffi/src/test/java/shinzo/cineffi/userCollectionAndScrapListTest.java
Labels: fix

#59 chore: Dockerfile 위치 변경 및 경로 내용 수정 #58
  Dockerfile
Labels: rename

#66 Feat/movie detail scrap#12
  cineffi/.idea/gradle.xml
  cineffi/.idea/modules.xml
  cineffi/.idea/modules/cineffi.main.iml
  cineffi/.idea/vcs.xml
  cineffi/build.gradle
  cineffi/src/main/java/shinzo/cineffi/auth/AuthController.java
  cineffi/src/main/java/shinzo/cineffi/config/EncryptUtil.java
  cineffi/src/main/java/shinzo/cineffi/config/SecurityConfig.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/CrewListDTO.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/InMovieDetailDTO.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/MovieDetailDTO.java
  cineffi/src/main/java/shinzo/cineffi/exception/message/ErrorMsg.java
  cineffi/src/main/java/shinzo/cineffi/movie/MovieController.java
  cineffi/src/main/java/shinzo/cineffi/movie/MovieService.java
  cineffi/src/main/java/shinzo/cineffi/movie/ScrapService.java
  cineffi/src/main/java/shinzo/cineffi/movie/repository/ActorMovieRepository.java
  cineffi/src/main/java/shinzo/cineffi/movie/repository/ScrapRepository.java
  cineffi/src/main/java/shinzo/cineffi/score/repository/ScoreRepository.java
  cineffi/src/main/resources/application.yml
Labels: feat

#70 Fix/following num bug#69
  cineffi/src/main/java/shinzo/cineffi/domain/entity/user/UserActivityNum.java
  cineffi/src/main/java/shinzo/cineffi/user/FollowService.java
Labels: bug

#72 Feat/movie detail scrap#12
  cineffi/src/main/java/shinzo/cineffi/config/InitService.java
  cineffi/src/main/java/shinzo/cineffi/movie/MovieInitService.java
  cineffi/src/main/resources/application.yml
Labels: refactor

#75 Feat/movie detail scrap#12
  cineffi/src/main/resources/application.yml
Labels: refactor

#77 refactor: 암복호화 로직 위치변경
  cineffi/src/main/java/shinzo/cineffi/Utils/EncryptUtil.java
  cineffi/src/main/java/shinzo/cineffi/movie/MovieController.java
Labels: refactor

#78 remove:암호화 복호화 테스트 코드 제거
  cineffi/src/main/java/shinzo/cineffi/movie/MovieController.java
Labels: test

#83 Test/box office dummy#12
  cineffi/src/main/java/shinzo/cineffi/config/InitService.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/movie/BoxOfficeMovie.java
  cineffi/src/main/java/shinzo/cineffi/movie/BoxOfficeDataHandler.java
Labels: test

#84 Fix: 영화 상세정보 감독, 배우 순서 교체#12
  cineffi/src/main/java/shinzo/cineffi/movie/MovieService.java
Labels: fix

#107 스프링 시큐리티 예외처리
  cineffi/build.gradle
  cineffi/src/main/java/shinzo/cineffi/config/SecurityConfig.java
  cineffi/src/main/java/shinzo/cineffi/jwt/JWTFilter.java
Labels: refactor

#109 JWTFilter 에러 수정 #81
  cineffi/src/main/java/shinzo/cineffi/jwt/JWTFilter.java
Labels: fix

#122 hotfix:springSecurity
  cineffi/src/main/java/shinzo/cineffi/auth/AuthController.java
  cineffi/src/main/java/shinzo/cineffi/auth/AuthService.java
  cineffi/src/main/java/shinzo/cineffi/jwt/JWTFilter.java
Labels: fix

#123 session 동기화 및 자잘한 문제 해결
  cineffi/src/main/java/shinzo/cineffi/chat/ChatController.java
  cineffi/src/main/java/shinzo/cineffi/chat/ChatService.java
  cineffi/src/main/java/shinzo/cineffi/chat/CinEffiWebSocketHandler.java
  cineffi/src/main/java/shinzo/cineffi/chat/repository/ChatroomRepository.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/chat/ChatMessage.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/chat/Chatroom.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/chat/ChatroomTag.java
Labels: feat, fix

#124 scheduleing for closing chatroom and backup
  cineffi/build.gradle
  cineffi/src/main/java/shinzo/cineffi/chat/ChatController.java
  cineffi/src/main/java/shinzo/cineffi/chat/ChatService.java
  cineffi/src/main/java/shinzo/cineffi/chat/CinEffiWebSocketHandler.java
  cineffi/src/main/java/shinzo/cineffi/chat/RedisMessageSubscriber.java
  cineffi/src/main/java/shinzo/cineffi/chat/repository/ChatroomRepository.java
  cineffi/src/main/java/shinzo/cineffi/config/CinEffiConfig.java
  cineffi/src/main/java/shinzo/cineffi/config/EncryptConfig.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/ChatroomBriefDTO.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/ChatroomDTO.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/chat/ChatMessage.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/chat/Chatroom.java
Labels: feat, fix

#130 카카오 로그인 에러 수정
  cineffi/src/main/java/shinzo/cineffi/auth/AuthController.java
  cineffi/src/main/java/shinzo/cineffi/auth/AuthService.java
Labels: fix

#133 액세스 토큰 만료시 토큰 재발급
  cineffi/src/main/java/shinzo/cineffi/jwt/JWTFilter.java
  cineffi/src/main/java/shinzo/cineffi/jwt/JWTUtil.java
Labels: fix

#135 chore: 배포 url 변경
  cineffi/src/main/resources/application.yml
Labels: chore

#145 채팅 모듈 탑재 완
  cineffi/src/main/java/shinzo/cineffi/chat/ChatController.java
  cineffi/src/main/java/shinzo/cineffi/chat/ChatService.java
  cineffi/src/main/java/shinzo/cineffi/chat/CinEffiWebSocketHandler.java
  cineffi/src/main/java/shinzo/cineffi/chat/repository/ChatroomRepository.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/GenreMovieListDTO.java
  cineffi/src/main/java/shinzo/cineffi/domain/dto/InListMovieDTO.java
  cineffi/src/main/java/shinzo/cineffi/domain/entity/user/User.java
  cineffi/src/main/java/shinzo/cineffi/movie/MovieService.java
Labels: feat, fix
